version: '3.7'
services:
  hashtopolis-server:
    container_name: hashtopolis-server
    build:
      context: .
      target: hashtopolis-server-prod
    restart: always
    volumes:
      - hashtopolis:/usr/local/share/hashtopolis:Z
    environment:
      HASHTOPOLIS_DB_USER: $MYSQL_USER
      HASHTOPOLIS_DB_PASS: $MYSQL_PASS
      HASHTOPOLIS_DB_HOST: $HASHTOPOLIS_DB_HOST
      HASHTOPOLIS_DB_DATABASE: $MYSQL_DATABASE
      HASHTOPOLIS_ADMIN_USER: $HASHTOPOLIS_ADMIN_USER
      HASHTOPOLIS_ADMIN_PASSWORD: $HASHTOPOLIS_ADMIN_PASSWORD
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  hashtopolis-web-ui:
    container_name: hashtopolis-web-ui
    image: hashtopolis-web-ui:latest
    restart: always
    depends_on: 
      - hashtopolis-server
    ports:
      - 4200:4200
volumes:
  db:
  hashtopolis:
