version: '3.7'
services:
  hashtopolis:
    container_name: hashtopolis
    build: .
    restart: always
    volumes:
      - hashtopolis:/usr/local/share/hashtopolis:Z
    environment:
      HASHTOPOLIS_DB_USER: $MYSQL_USER
      HASHTOPOLIS_DB_PASS: $MYSQL_PASS
      HASHTOPOLIS_DB_HOST: db
      HASHTOPOLIS_DB_DATABASE: $MYSQL_DB
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASS
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
    cap_drop:
      - ALL
    cap_add:
      # used to change files since non-priv user
      - CHOWN
      # used because container uses find command
      - CAP_DAC_READ_SEARCH
      # used for the gosu binary
      - CAP_SETGID
      - CAP_SETUID
volumes:
  db:
  hashtopolis:
