version: "3.7"
services:
  hashtopolis-server:
    container_name: hashtopolis-server
    build:
      context: ..
      target: hashtopolis-server-dev
      args:
        - CONTAINER_USER_CMD_PRE
        - CONTAINER_USER_CMD_POST
    environment:
      HASHTOPOLIS_DB_USER: hashtopolis
      HASHTOPOLIS_DB_PASS: hashtopolis
      HASHTOPOLIS_DB_HOST: db
      HASHTOPOLIS_DB_DATABASE: hashtopolis
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/var/www/html
    networks:
      - hashtopolis_dev
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hashtopolis
      MYSQL_DATABASE: hashtopolis
      MYSQL_USER: hashtopolis
      MYSQL_PASSWORD: hashtopolis
    networks:
      - hashtopolis_dev
volumes:
  db:

networks:
  hashtopolis_dev:
    # This network will also be used by the python-agent
    name: hashtopolis_dev
