version: "3"
services:
  hashtopolis:
    container_name: hashtopolis_dev
    # Uncomment the next line to use a non-root user. On Linux, this will prevent
    # new files getting created as root, but you may need to update the USER_UID
    # and USER_GID in .devcontainer/Dockerfile to match your user if not 1000.
    # user: vscode
    # Using a Dockerfile is optional, but included for completeness.
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      # This is where VS Code should expect to find your project's source code
      # and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/var/www/html
    # Overrides default command so things don't shut down after the process ends.
    command: docker-php-entrypoint apache2-foreground
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hashtopolis
      MYSQL_DATABASE: hashtopolis
      MYSQL_USER: hashtopolis
      MYSQL_PASSWORD: hashtopolis
    cap_drop:
      - ALL
    cap_add:
      # used to change files since non-priv user
      - CHOWN
      # used because container uses find command
      - CAP_DAC_READ_SEARCH
      # used for the gosu binary
      - CAP_SETGID
      - CAP_SETUID
volumes:
  db:
